[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "flask-socketio>=5.5.1",
    "psutil>=7.0.0",
    "python-telegram-bot>=22.1",
]
